name: 🔒 Test Secrets
on: workflow_dispatch

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "EC2 host: ${{ secrets.EC2_HOST }}"
          echo "DockerHub user: ${{ secrets.DOCKERHUB_USER }}"
          echo "Length of SSH key: $(echo '${{ secrets.EC2_SSH_KEY }}' | wc -c)"
